### ISSUE TITLE
Better control of cropped image size

### ISSUE THREAD

**Issue by Roy-Orbison** [k3b/LosslessJpgCrop#31] opened 2021-02-27 13:18 UTC
Please add a dialogue box to crop to common image aspect ratios (16:9, 1:1, etc.), preferably accompanied by two input boxes that show and allow adjustment of the output width and height. At the moment it's virtually impossible to get a precise size.

**Comment by Roy-Orbison** [comment] 2021-02-27 14:43
Alternatively, you could show a constant status line or overlay with the output size, and allow pinch to zoom to enable fine adjustment. Snapping to an aspect ratio by choosing which dimension to "lock" would be great, e.g. crop an 18:9 screenshot to 16:9 by fixing its height at 1080.

**Comment by k3b** [comment] 2021-03-01 14:22
Closed as duplicate of #15

**Closed by k3b** 2021-03-01 14:22 UTC
